# Generated by Django 5.1.2 on 2024-11-08 09:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Shopify", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="patrocinador",
            old_name="descipcion",
            new_name="descripcion",
        ),
    ]
