# Generated by Django 5.1.2 on 2024-11-21 19:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Shopify", "0002_rename_descipcion_patrocinador_descripcion"),
    ]

    operations = [
        migrations.CreateModel(
            name="Publicidad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=64)),
                ("descripcion", models.CharField(max_length=354)),
                ("precio", models.IntegerField()),
                ("url", models.CharField(max_length=264)),
            ],
        ),
    ]
