# Generated by Django 5.1.2 on 2024-11-21 20:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Shopify", "0003_publicidad"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patrocinador",
            name="descripcion",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="publicidad",
            name="descripcion",
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name="publicidad",
            name="url",
            field=models.URLField(),
        ),
    ]
