# Generated by Django 5.1.2 on 2024-11-21 20:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Shopify", "0004_alter_patrocinador_descripcion_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="publicidad",
            name="imagen",
            field=models.ImageField(blank=True, null=True, upload_to="publicidad"),
        ),
        migrations.AlterField(
            model_name="publicidad",
            name="descripcion",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
