# Generated by Django 5.1.2 on 2024-11-21 21:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Shopify", "0005_publicidad_imagen_alter_publicidad_descripcion"),
    ]

    operations = [
        migrations.AddField(
            model_name="publicidad",
            name="region",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
