# Generated by Django 5.1.2 on 2024-11-24 19:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Shopify", "0006_publicidad_region"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publicidad",
            name="precio",
            field=models.CharField(max_length=64),
        ),
    ]
