# Generated by Django 5.1.2 on 2024-11-24 19:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Shopify", "0007_alter_publicidad_precio"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="publicidad",
            name="url",
        ),
    ]
