# Generated by Django 5.1.2 on 2024-11-24 19:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Shopify", "0008_remove_publicidad_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="publicidad",
            name="url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
