# Generated by Django 5.1.2 on 2024-11-24 20:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Shopify", "0009_publicidad_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publicidad",
            name="imagen",
            field=models.ImageField(blank=True, null=True, upload_to="publicidad/"),
        ),
    ]
