# Generated by Django 5.1.2 on 2024-10-30 16:27

import Equipo.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Equipo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=64)),
                (
                    "escudo",
                    models.ImageField(blank=True, null=True, upload_to="escuderia/"),
                ),
                ("poblacion", models.CharField(blank=True, max_length=64, null=True)),
                ("activo", models.BooleanField(default=True)),
                ("vacio", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Jugador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=64)),
                ("edad", models.IntegerField()),
                ("nacionalidad", models.CharField(max_length=64)),
                (
                    "posicion",
                    models.CharField(
                        choices=[
                            ("portero", "Portero"),
                            ("defensa_lateral_izquierdo", "Defensa Lateral Izquierdo"),
                            ("defensa_central", "Defensa Central"),
                            ("defensa_lateral_derecho", "Defensa Lateral Derecho"),
                            ("medio_centro", "Medio Centro"),
                            ("medio_centro_defensivo", "Medio Centro Defensivo"),
                            ("medio_centro_ofensivo", "Medio Centro Ofensivo"),
                            ("extremo_izquierdo", "Extremo Izquierdo"),
                            ("delantero_centro", "Delantero Centro"),
                            ("extremo_derecho", "Extremo Derecho"),
                        ],
                        max_length=64,
                    ),
                ),
                (
                    "equipo",
                    models.ForeignKey(
                        default=Equipo.models.get_default_equipo,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        to="Equipo.equipo",
                    ),
                ),
            ],
        ),
    ]
