# Generated by Django 5.1.2 on 2024-10-30 21:51

import Equipo.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Equipo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugador',
            name='equipo',
            field=models.ForeignKey(default=Equipo.models.get_default_equipo, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='jugador', to='Equipo.equipo'),
        ),
    ]
