# Generated by Django 5.1.2 on 2024-10-30 22:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Equipo", "0002_alter_jugador_equipo"),
    ]

    operations = [
        migrations.AddField(
            model_name="jugador",
            name="vacio",
            field=models.BooleanField(default=False),
        ),
    ]
