# Generated by Django 5.1.2 on 2024-11-03 19:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Equipo", "0003_jugador_vacio"),
    ]

    operations = [
        migrations.AddField(
            model_name="jugador",
            name="numero",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
