# Generated by Django 5.1.2 on 2024-11-05 21:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Equipo", "0004_jugador_numero"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jugador",
            name="edad",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="jugador",
            name="nacionalidad",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
