# Generated by Django 5.1.2 on 2024-10-30 21:55

import Torneo.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("Equipo", "0002_alter_jugador_equipo"),
        ("Shopify", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Champions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_inicio", models.DateTimeField()),
                ("fecha_final", models.DateTimeField()),
                ("empezado", models.BooleanField(default=False)),
                ("finalizado", models.BooleanField(default=False)),
                ("completo", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Liga_V2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nota_corte", models.IntegerField()),
                ("empezado", models.BooleanField(default=False)),
                ("finalizado", models.BooleanField(default=False)),
                ("fecha_inicio", models.DateTimeField()),
                ("fecha_final", models.DateTimeField()),
                ("completo", models.BooleanField(default=False)),
                (
                    "champions",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="liga_v2",
                        to="Torneo.champions",
                    ),
                ),
                (
                    "equipos",
                    models.ManyToManyField(
                        blank=True,
                        null=True,
                        related_name="liga_v2",
                        to="Equipo.equipo",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Grupo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=64)),
                ("completo", models.BooleanField(default=False)),
                (
                    "equipos",
                    models.ManyToManyField(
                        blank=True, null=True, related_name="grupo", to="Equipo.equipo"
                    ),
                ),
                (
                    "liga",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grupo",
                        to="Torneo.liga_v2",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Torneo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=64)),
                ("fecha_inicio", models.DateTimeField()),
                ("fecha_final", models.DateTimeField()),
                ("empezado", models.BooleanField(default=False)),
                ("finalizado", models.BooleanField(default=False)),
                ("descripcion", models.CharField(max_length=256)),
                ("completo", models.BooleanField(default=False)),
                (
                    "ganador",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="torneo_ganador",
                        to="Equipo.equipo",
                    ),
                ),
                (
                    "patrocinadores",
                    models.ManyToManyField(
                        related_name="torneo", to="Shopify.patrocinador"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="champions",
            name="torneo",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="champions",
                to="Torneo.torneo",
            ),
        ),
        migrations.CreateModel(
            name="Bracket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bracket_32",
                    models.JSONField(default=Torneo.models.get_list_default_32),
                ),
                (
                    "bracket_16",
                    models.JSONField(default=Torneo.models.get_list_default_16),
                ),
                (
                    "bracket_8",
                    models.JSONField(default=Torneo.models.get_list_default_8),
                ),
                (
                    "bracket_4",
                    models.JSONField(default=Torneo.models.get_list_default_4),
                ),
                (
                    "bracket_2_final",
                    models.JSONField(default=Torneo.models.get_list_default_2),
                ),
                (
                    "bracket_2_perdedor",
                    models.JSONField(default=Torneo.models.get_list_default_2),
                ),
                (
                    "ronda",
                    models.CharField(
                        choices=[
                            ("32", "32"),
                            ("16", "16"),
                            ("8", "8"),
                            ("4", "4"),
                            ("2", "2"),
                        ],
                        default="32",
                        max_length=10,
                    ),
                ),
                ("fecha_inicio", models.DateTimeField()),
                ("fecha_final", models.DateTimeField()),
                ("empezado", models.BooleanField(default=False)),
                ("finalizado", models.BooleanField(default=False)),
                (
                    "champions",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bracket",
                        to="Torneo.champions",
                    ),
                ),
                (
                    "torneo",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bracket",
                        to="Torneo.torneo",
                    ),
                ),
            ],
        ),
    ]
