# Generated by Django 5.1.2 on 2024-11-04 19:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Equipo", "0004_jugador_numero"),
        ("Torneo", "0002_remove_bracket_bracket_16_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="torneo",
            name="equipos",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="torneo", to="Equipo.equipo"
            ),
        ),
    ]
