# Generated by Django 5.1.2 on 2024-11-05 21:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Torneo", "0003_torneo_equipos"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="champions",
            name="completo",
        ),
        migrations.RemoveField(
            model_name="grupo",
            name="completo",
        ),
        migrations.RemoveField(
            model_name="liga_v2",
            name="completo",
        ),
        migrations.RemoveField(
            model_name="torneo",
            name="completo",
        ),
    ]
