# Generated by Django 5.1.2 on 2024-11-05 22:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Torneo", "0004_remove_champions_completo_remove_grupo_completo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="torneo",
            name="fecha_final",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="torneo",
            name="fecha_inicio",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
