# Generated by Django 5.1.2 on 2024-11-05 23:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Shopify", "0001_initial"),
        ("Torneo", "0006_alter_champions_fecha_final_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bracket",
            name="fecha_final",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="bracket",
            name="fecha_inicio",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="liga_v2",
            name="fecha_final",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="liga_v2",
            name="fecha_inicio",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="torneo",
            name="patrocinadores",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="torneo", to="Shopify.patrocinador"
            ),
        ),
    ]
