# Generated by Django 5.1.2 on 2024-11-07 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Torneo", "0008_bracket_equipo"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bracket",
            old_name="ronda",
            new_name="jugadores",
        ),
        migrations.AddField(
            model_name="bracket",
            name="finales",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="bracket",
            name="champions",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bracket",
                to="Torneo.champions",
            ),
        ),
    ]
