# Generated by Django 5.1.2 on 2024-11-12 23:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Torneo", "0009_rename_ronda_bracket_jugadores_bracket_finales_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bracket",
            name="jugadores",
        ),
        migrations.AddField(
            model_name="torneo",
            name="numero_alineacion",
            field=models.CharField(
                choices=[("7", "7"), ("11", "11")], default="7", max_length=5
            ),
        ),
    ]
