# Generated by Django 5.1.2 on 2024-11-14 15:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Torneo", "0010_remove_bracket_jugadores_torneo_numero_alineacion"),
    ]

    operations = []
