# Generated by Django 5.1.2 on 2024-11-18 12:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Torneo", "0011_merge_20241114_1628"),
    ]

    operations = [
        migrations.AlterField(
            model_name="liga_v2",
            name="nota_corte",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="torneo",
            name="descripcion",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
