# Generated by Django 5.1.2 on 2024-11-19 17:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Torneo", "0012_alter_liga_v2_nota_corte_alter_torneo_descripcion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="torneo",
            name="numero_alineacion",
            field=models.CharField(
                choices=[("7", "7"), ("11", "11")], default="11", max_length=5
            ),
        ),
    ]
