# Generated by Django 5.1.2 on 2024-12-19 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Torneo', '0013_alter_torneo_numero_alineacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='champions',
            name='plata',
            field=models.BooleanField(default=False),
        ),
    ]
