# Generated by Django 5.1.2 on 2024-11-04 16:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Equipo", "0004_jugador_numero"),
        (
            "Partido",
            "0002_partido_localizacion_partido_partes_partido_penaltis_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="partido",
            name="equipos",
            field=models.ManyToManyField(related_name="partido", to="Equipo.equipo"),
        ),
    ]
