# Generated by Django 5.1.2 on 2024-11-04 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Equipo", "0004_jugador_numero"),
        ("Partido", "0003_partido_equipos"),
    ]

    operations = [
        migrations.AddField(
            model_name="partido",
            name="ganador",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="partido_ganado",
                to="Equipo.equipo",
            ),
        ),
    ]
