# Generated by Django 5.1.2 on 2024-11-05 21:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Partido", "0004_partido_ganador"),
    ]

    operations = [
        migrations.AlterField(
            model_name="partido",
            name="minutos_jugados",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="partido",
            name="tiempo_extra",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
