# Generated by Django 5.1.2 on 2024-11-08 11:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Partido", "0006_partido_torneo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="partido",
            name="marcador_1",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="partido",
            name="marcador_2",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
