# Generated by Django 5.1.2 on 2024-11-11 13:00

import Partido.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Equipo", "0005_alter_jugador_edad_alter_jugador_nacionalidad"),
        ("Partido", "0007_alter_partido_marcador_1_alter_partido_marcador_2"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="alineacion_7",
            name="equipo",
        ),
        migrations.RemoveField(
            model_name="alineacion_7",
            name="jugador_1",
        ),
        migrations.RemoveField(
            model_name="alineacion_7",
            name="jugador_2",
        ),
        migrations.RemoveField(
            model_name="alineacion_7",
            name="jugador_3",
        ),
        migrations.RemoveField(
            model_name="alineacion_7",
            name="jugador_4",
        ),
        migrations.RemoveField(
            model_name="alineacion_7",
            name="jugador_5",
        ),
        migrations.RemoveField(
            model_name="alineacion_7",
            name="jugador_6",
        ),
        migrations.RemoveField(
            model_name="alineacion_7",
            name="jugador_7",
        ),
        migrations.RemoveField(
            model_name="alineacion_7",
            name="jugadores",
        ),
        migrations.RemoveField(
            model_name="alineacion_7",
            name="partido",
        ),
        migrations.CreateModel(
            name="Alineacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("posiciones", models.JSONField(blank=True, null=True)),
                (
                    "equipo",
                    models.ForeignKey(
                        default=Partido.models.get_default_equipo,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        related_name="alineacion",
                        to="Equipo.equipo",
                    ),
                ),
                (
                    "jugadores",
                    models.ManyToManyField(
                        blank=True,
                        null=True,
                        related_name="alineacion",
                        to="Equipo.jugador",
                    ),
                ),
                (
                    "partido",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="alineacion",
                        to="Partido.partido",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Alineacion_11",
        ),
        migrations.DeleteModel(
            name="Alineacion_7",
        ),
    ]
