# Generated by Django 5.1.2 on 2024-11-11 13:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Partido", "0008_remove_alineacion_7_equipo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="partido",
            name="descripcion",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
