# Generated by Django 5.1.2 on 2024-11-12 21:48

import Partido.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Partido", "0009_alter_partido_descripcion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evento",
            name="partido",
            field=models.ForeignKey(
                default=Partido.models.get_default_partido,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="evento",
                to="Partido.partido",
            ),
        ),
        migrations.AlterField(
            model_name="partido",
            name="nombre",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
