# Generated by Django 5.1.2 on 2024-11-12 21:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Partido", "0010_alter_evento_partido_alter_partido_nombre"),
    ]

    operations = [
        migrations.AlterField(
            model_name="partido",
            name="numero_alineacion",
            field=models.CharField(
                blank=True, choices=[("7", "7"), ("11", "11")], max_length=5, null=True
            ),
        ),
    ]
