# Generated by Django 5.1.2 on 2024-11-12 23:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Equipo", "0005_alter_jugador_edad_alter_jugador_nacionalidad"),
        ("Partido", "0011_alter_partido_numero_alineacion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="partido",
            name="equipos",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="partido", to="Equipo.equipo"
            ),
        ),
    ]
