# Generated by Django 5.1.2 on 2024-11-13 23:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Partido", "0012_alter_partido_equipos"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="partido",
            name="tiempo_extra",
        ),
        migrations.AddField(
            model_name="evento",
            name="posicion_expulsion",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="partido",
            name="minutos_jugados_extra",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="partido",
            name="partes_extra",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="evento",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("tarjeta_amarilla", "Tarjeta Amarilla"),
                    ("tarjeta_roja", "Tarjeta Roja"),
                    ("gol", "Gol"),
                    ("falta", "Falta"),
                    ("corner", "Corner"),
                    ("penalti_gol", "Penalti - Gol"),
                    ("penalti_fallo", "Penalti - Fallo"),
                    ("sustitucion", "Sustitución"),
                    ("asistencia", "Asistencia"),
                    ("lesion", "Lesión"),
                    ("tarjeta_azul", "Tarjeta Azul"),
                    ("tiempo_anadido", "Tiempo Añadido"),
                ],
                max_length=64,
            ),
        ),
    ]
