# Generated by Django 5.1.2 on 2024-11-21 19:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Partido", "0014_alineacion_orden"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alineacion",
            name="orden",
            field=models.CharField(
                blank=True,
                choices=[
                    ("4-4-2", "4-4-2"),
                    ("4-3-3", "4-3-3"),
                    ("3-5-2", "3-5-2"),
                    ("4-2-3-1", "4-2-3-1"),
                    ("5-3-2", "5-3-2"),
                ],
                max_length=64,
                null=True,
            ),
        ),
    ]
