# Generated by Django 5.1.2 on 2024-11-23 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Partido", "0015_alter_alineacion_orden"),
        ("Torneo", "0013_alter_torneo_numero_alineacion"),
    ]

    operations = [
        migrations.AddField(
            model_name="partido",
            name="grupo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="partido",
                to="Torneo.grupo",
            ),
        ),
    ]
