# Generated by Django 5.1.2 on 2024-11-25 10:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Partido", "0016_partido_grupo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="partido",
            name="marcador_1",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="partido",
            name="marcador_2",
            field=models.IntegerField(default=0),
        ),
    ]
