# Generated by Django 5.1.2 on 2024-12-06 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Partido', '0018_alter_evento_equipo_alter_evento_hora_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='hora',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
