# Generated by Django 5.1.2 on 2024-10-30 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("Equipo", "0001_initial"),
        ("Shopify", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Liga",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=64)),
                ("empezado", models.BooleanField(default=False)),
                ("finalizado", models.BooleanField(default=False)),
                ("fecha_inicio", models.DateTimeField()),
                ("fecha_final", models.DateTimeField()),
                (
                    "tipo",
                    models.CharField(
                        choices=[("ida", "Ida"), ("ida_vuelta", "Ida y vuelta")],
                        max_length=64,
                    ),
                ),
                ("descripcion", models.CharField(max_length=256)),
                (
                    "equipos",
                    models.ManyToManyField(related_name="liga", to="Equipo.equipo"),
                ),
                (
                    "ganador",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="liga_ganador",
                        to="Equipo.equipo",
                    ),
                ),
                ("patrocinadores", models.ManyToManyField(to="Shopify.patrocinador")),
            ],
        ),
    ]
