# Generated by Django 5.1.2 on 2024-10-30 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Liga', '0001_initial'),
        ('Shopify', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liga',
            name='patrocinadores',
            field=models.ManyToManyField(related_name='liga', to='Shopify.patrocinador'),
        ),
    ]
