# Generated by Django 5.1.2 on 2024-11-03 19:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Liga", "0002_alter_liga_patrocinadores"),
        ("Shopify", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="liga",
            name="imagen",
            field=models.ImageField(blank=True, null=True, upload_to="liga/"),
        ),
        migrations.AddField(
            model_name="liga",
            name="localizacion",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="liga",
            name="organizador",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="liga",
            name="descripcion",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="liga",
            name="fecha_final",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="liga",
            name="fecha_inicio",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="liga",
            name="patrocinadores",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="liga", to="Shopify.patrocinador"
            ),
        ),
    ]
