# Generated by Django 5.1.2 on 2024-11-15 17:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Liga", "0003_liga_imagen_liga_localizacion_liga_organizador_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="liga",
            name="numero_alineacion",
            field=models.CharField(
                choices=[("7", "7"), ("11", "11")], default="7", max_length=5
            ),
        ),
    ]
